name: Deploy to Firebase Hosting (Preview + Live)

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  build_and_preview:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KAMEOS_OSTHEOPATIE }}
          projectId: kameos-ostheopatie
          channelId: preview

  build_and_live:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KAMEOS_OSTHEOPATIE }}
          channelId: live
          projectId: kameos-ostheopatie
